# Generated by Django 4.0.3 on 2022-07-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured', models.BooleanField()),
                ('hash_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_name', models.CharField(max_length=200, null=True)),
                ('acronym', models.CharField(blank=True, max_length=200, null=True)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('organization_url', models.URLField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('startTime', models.DateField(blank=True, null=True)),
                ('endtime', models.DateField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('in_person', models.BooleanField(blank=True, null=True)),
                ('virtual', models.BooleanField(blank=True, null=True)),
                ('cfp_due_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('code_of_conduct_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
