# Generated by Django 4.0.3 on 2022-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured', models.BooleanField()),
                ('hash_tag', models.CharField(max_length=200)),
            ],
        ),
    ]
