# Generated by Django 4.0.3 on 2022-07-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='acronym',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cfp_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='code_of_conduct_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='conference_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='in_person',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organization_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organization_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hash_tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
