# Generated by Django 4.0.3 on 2022-07-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startTime',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
