# Generated by Django 4.0.3 on 2022-07-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_enddate_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessibility_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteering_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
