# Generated by Django 4.0.3 on 2022-07-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_acronym_alter_event_cfp_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
