# Generated by Django 4.0.3 on 2022-07-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
