# Generated by Django 4.0.3 on 2022-08-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cfp_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price_range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
