# Generated by Django 4.0.3 on 2022-08-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_cfp_url_event_image_url_event_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
