# Generated by Django 4.0.3 on 2022-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
