# Generated by Django 4.0.3 on 2022-12-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
