# Generated by Django 4.0.3 on 2023-01-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
