# Generated by Django 4.0.3 on 2023-01-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='continent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
